version: '3.8'

services:
  app:
    container_name: follow-service-docker
    image: follow-service-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/follows_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    container_name: follows-db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: follows_db
